### ISSUE TITLE
Can't encrypt secret that starts with dash

### ISSUE THREAD

**Issue by gregnr** [launchcodedev/app-config#118]
# Problem
When trying to encrypt a secret value that starts with a dash `-`, app-config throws an error.

# Expected behaviour
App-config successfully encrypts the value.

# Details
For example, if trying to encrypt `"--my-value--"`:
```bash
app-config secret encrypt "--my-value--" # Note that the value is wrapped in double quotes
...
Unknown arguments: my-value--, myValue
```
It appears the CLI doesn't consider the quotes wrapped around the value and is evaluating as an argument. Not sure if this is a `yargs` problem, or something we are doing.

# Context
This was originally discovered when trying to encrypt an SSH private key that looks like:
```
-----BEGIN OPENSSH PRIVATE KEY-----
...
-----END OPENSSH PRIVATE KEY-----
```

**Comment by joelgallant** [comment]
This is a yargs problem. A workaround is to use stdin or the clipboard option.

**Comment by gregnr** [comment]
Thanks 👍
