### ISSUE TITLE
Integrate react-native plugin w/ an example project

### ISSUE THREAD

**Issue by joelgallant** [launchcodedev/app-config#13]
- [x] Metro loader plugin
- [x] Add an example project
- [x] Use nohoist in example project to avoid workspace weirdness
- [ ] Provide options for loadConfig (eg. fileBaseName)
- [ ] Support fast refresh without full app reload

Work is in PR #7

**Comment by joelgallant** [comment]
I don't think the remaining items should block a v2. Thoughts, @gregnr ?

**Comment by gregnr** [comment]
Yeah I think our current MVP is enough for v2.

**Comment by joelgallant** [comment]
#123 #143 covers the rest
