### ISSUE TITLE
Support APP_CONFIG_SECRETS_KEY_FILE

### ISSUE THREAD

**Issue by gregnr** [launchcodedev/app-config#163]
There are many CI systems that support file injection (in addition to environment variable injection). They usually work by injecting the file into a temporary directory, then populating the environment variable of choice with the temporary file path.

The most common pattern I've seen is to have a `MY_ENV` and a `MY_ENV_FILE` env variables that are mutually exclusive (eg. Pulumi - https://github.com/pulumi/pulumi/issues/5305).

On that note it would be great to support a `APP_CONFIG_SECRETS_KEY_FILE` in addition to `APP_CONFIG_SECRETS_KEY` which will contain the file path to the secrets key.

**Comment by joelgallant** [comment]
The same could be said about k8s secrets as well. Good idea.
