### ISSUE TITLE
Option to not load any config at Webpack build time

### ISSUE THREAD

**Issue by gregnr** [launchcodedev/app-config#174]
Currently it appears that the `app-config` webpack plugin will always load config at build time, regardless of whether header injection is enabled (please correct me if I'm wrong).

LC uses the secret encryption heavily, and we're running into issues in CI where we want to build our webpack bundles (via a Docker build), but don't really care/want to load config at build time since we use header injection at runtime. Since we are using secret encryption, CI fails to build the webpack bundle since it doesn't (by default) have a key available to decrypt the `app-config` secrets.

We are able to solve this by injecting a CI `APP_CONFIG_SECRETS_KEY` into our CI jobs _and_ in our Dockerfiles as a build arg, but this feels ultimately unnecessary since we don't actually care about the config at build time anyway.

Thoughts on adding a flag to skip build time config injection entirely if used along with header injection? Any downsides to providing this option?

**Comment by joelgallant** [comment]
I think there are downsides to this being the default, since normally you'd want bundles to include some "default config" (production).

But, a flag to do this is entirely reasonable, as long as you **know** that you'll be injecting config at runtime.

**Comment by joelgallant** [comment]
I'm looking into this (as a part of #176), but it'll be more complicated than it sounds. We currently rely on `loadValidatedConfig`, because we need `validationFunctionCode` to generate the AJV validation function. So at the least, we'd need to load schema & currentEnvironment separately.

As for the config value itself - I'm thinking just make it `new Error('unfilled config')` or something so it's obvious?

**Comment by gregnr** [comment]
Right, didn't realize `loadValidatedConfig` was the only way to get those extra values. Or is that just for convenience?

Yes I agree we need some sort of error fallback for cases where config was never injected. A simple error makes sense. Alternatively one could make the argument to rethink the whole `loadConfig` requirement on frontend (where you need it for Node.js, but currently not needed for frontend), since it can be used here as an explicit/required validation mechanism (ie. always validate at runtime). Would also provide a nice consistency across the stack. Of course this would be a breaking change and probably introduces a bunch of new complexities.

**Comment by joelgallant** [comment]
I think it'll be possible to split it up, since loadValidatedConfig is really just a shortcut for loadUnvalidatedConfig + validateConfig.

We could do something fancier like we do in Node.js, with a Proxy that throws out an error if you try and access anything. That does make IE support harder of course.

I don't think it's worthwhile to require loadConfig though, given that we're serving an edge case of users who "know what they're doing".

**Comment by gregnr** [comment]
Makes sense. With regard to proxy, can we do both? Throw an error on startup if config does not exist (to support cases where proxy isn't supported), _and_ throw an error when trying to access the variable (when proxy is supported)? I don't know if it's possible to gracefully fallback if proxies aren't supported. 

For runtime validation, how is this currently done for split config (eg. config that comes from query params, acts as feature flags, etc)?

**Comment by joelgallant** [comment]
> Makes sense. With regard to proxy, can we do both? Throw an error on startup if config does not exist (to support cases where proxy isn't supported), _and_ throw an error when trying to access the variable (when proxy is supported)? I don't know if it's possible to gracefully fallback if proxies aren't supported.

I think we could play around with the possibilities - something like throwing a module-level error might be perfectly reasonable.

> For runtime validation, how is this currently done for split config (eg. config that comes from query params, acts as feature flags, etc)? Do you just manually call the validation function on startup?

The validation function is entirely separate, for bundled app-config. That way, you load up config (including any overrides) _then_ validate it (using the `validateConfig` export).
