### ISSUE TITLE
Optionally support using unix sockets for secret-agent communication

### ISSUE THREAD

**Issue by gregnr** [launchcodedev/app-config#22]
Consider binding the secrets agent to a Unix socket, similar to how  [ssh-agent](https://man.openbsd.org/ssh-agent.1) works. Offers stronger/more flexible security via Unix user permissions system (eg. on a multi-tenant host). Also will see minor performance increases (no TCP overhead). 

Will need to consider how this will work on Windows. Perhaps port binding as a fallback.

**Comment by joelgallant** [comment]
The `ws` library supports this actually. It's as easy as adding `ws+unix:///` in the URL. We could detect if we're on a posix environment and use that. ([docs](https://github.com/websockets/ws/blob/HEAD/doc/ws.md#unix-domain-sockets))

**Comment by joelgallant** [comment]
Note that we save the `port` to the user's settings file already, so it wouldn't be a lot of work to make this configurable (and make a smart decision by default first-try).

Also worth mentioning that security wise, it is TLS. The way it is somewhat insecure, is that it'll decrypt secrets from anyone who can access the localhost port (it's hard to have a notion of "user" here). I think I've spelled that out in documentation, but might need better wording. And of course, this is a minor thing (to me) - I don't remember the last time I've really seen a multi-user dev machine (secret-agent isn't for production).

**Comment by joelgallant** [comment]
Sort of related https://github.com/launchcodedev/ws-rpc/pull/1
