### ISSUE TITLE
Consider "reserving" $ keys (`$foo`) so that adding new directives isn't technically a breaking change

### ISSUE THREAD

**Issue by joelgallant** [launchcodedev/app-config#33]
If we wanted to add new directives in the future, it would be a breaking change (since old `$foo` keys would then be treated differently). If we reserve this "namespace" for special keys, it's not an awkward situation to add new directives. Basically, just error out when we see keys like this in a fully parsed object.

**Comment by gregnr** [comment]
I agree this is a good idea. If someone really wanted a `$` prefixed key, do we want to support something like:
```yaml
$raw:
  $myKey: 123
```
Perhaps the above `$raw` directive escapes all nested directives/extensions?

**Comment by joelgallant** [comment]
That was my thought too - a directive like `$raw` or just demarking keys like `$$myKey`? The implementation of that would actually be elegant (with one parsing extension to handle unescaping, mark a meta property like 'wasEscaped', then the key checker at the end just has to check for 'wasEscaped').

**Comment by gregnr** [comment]
Demarking is probably a better idea than `$raw`, so that we can support nested directives/extensions.
