### ISSUE TITLE
Add Electron package for injecting config into web apps

### ISSUE THREAD

**Issue by joelgallant** [launchcodedev/app-config#57]
At LC, we had a small internal package that included this functionality. It would be nice to make an open source utility for injecting app config values into web apps in Electron. This can be done via preload scripts (so it has access to 'fs' and other Node imports).

**Comment by joelgallant** [comment]
@johnb8 you'd be the closest at LC to this. any thoughts on how this work could be done as a separate entity?

**Comment by johnb8** [comment]
I think we could just make a new package that can load the config and make it available to the main web page through the contextBridge. That script would need to be added to the preload of any BrowserWindows. A function that generates the options that need to be added to the BrowserWindow and can merge any existing options would be nice too. You'd need to add those options to every BrowserWindow you make (might not be too annoying), but I'm not sure how common it is to make multiple BrowserWindows or if there's a more global way to make the config available.

Currently we need to use `$extends` in the external app config file to merge with the default bundled file. It would be nice if app config could merge the external config with the default bundled config without it. It would also be nice if the external config didn't need to be called .app-config.yml. It might be useful to search multiple locations for a config too. Not sure if there's already stuff in app config that can do any of that.
