### ISSUE TITLE
App Config on Multiple Devices

### ISSUE THREAD

**Issue by daniel-zarinski** [launchcodedev/app-config#61]
What happens when a user has multiple devices but the same email? Came across this scenario while using my local machine (windows pc running wsl2) and trying to develop on an existing project.

Both devices have the same app-config email and name (different private/public keys)

What's the best approach here? 
Perhaps when initializing app-config secrets it will also allow for a device name? Or default it to current device name and allow user to override? 
Alternatively the user can just append a device name to their name manually.

**Comment by joelgallant** [comment]
That's funny, I've mulled this over already. My first instinct is to add a third field in app-config.meta file (`device` or `keyName`). This can default to hostname, and be initialized as a comment or something similar.

The other option here is sharing keys between computers (like you could with gpg keys). Providing a CLI mechanism to help with this is possible.

**Comment by daniel-zarinski** [comment]
Both options are great. 

## Option 1 - additional key
Was thinking the same thing. This option is nice and allows the user to identify which of their devices should get access. It also acts nicely in the event that one of their machines is compromised. 
(Might need to add some additional logic to the untrust command if there are 2 users with the same email)

## Option 2 - Sharing keys
Would be nice to have a cli command to either print the path of where keys are stored (after a week I forgot lol) Or print them out to shell?

**Comment by joelgallant** [comment]
Agreed on all points. A print command sounds reasonable. Not sure what the DX should be with 2 users with the same email, I guess it can just prompt.

**Comment by daniel-zarinski** [comment]
Thoughts on additional prompt asking for `device` or `keyName`? 

Or

Not sure how difficult it is to display an option group and prompt user to select which device they want to untrust. The list will render all users w/ that email and their associated device or keyName

**Comment by joelgallant** [comment]
https://www.npmjs.com/package/prompts#multiselectmessage-choices-initial-max-hint-warn

Your example makes sense to me. I imagine the normal workflow of untrusting will be to untrust _all_ for a given user, so it should be a multiselect.

**Comment by daniel-zarinski** [comment]
OH, cool! That's easier than I imagined lol

Makes sense to me to untrust all devices associated to the email since that's probably the common use case.

I was imagining a scenario where a single device gets compromised so you might want to untrust 1 device instead of all. 
For example, a month from now maybe I'll want to remove access to my windows machine but still keep my macos trusted, so it'd be nice to allow that flexibility.
