### ISSUE TITLE
Consider building a plugin for cypress.io

### ISSUE THREAD

**Issue by joelgallant** [launchcodedev/app-config#80]
Currently, as user would have to use our webpack plugin and a [preprocessor](https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor). I think we could build something simple that alleviates that need, and potentially ties in to cypress closer.

**Comment by daniel-zarinski** [comment]
I agree.

I was reading up on their plugin documentations and saw this,
https://github.com/morficus/cypress-dotenv
