### ISSUE TITLE
Unhelpful error when using an invalid config with webpack-dev-server

### ISSUE THREAD

**Issue by johnb8** [launchcodedev/app-config#88]
Running `webpack-dev-server` in a project using webpack and the app-config webpack plugin with an invalid app-config config gives an unhelpful `This dependency was not found: @lcdev/appconfig` error. It would be nice if app-config errors could be shown as well, like when just running `webpack`. Not sure if that's a limitation of `webpack-dev-server`, but it should probably be documented somewhere at least.

**Comment by joelgallant** [comment]
You're using CleanWebpackPlugin or something too? When running our example project, I see the following:

![01-13-1610543969](https://user-images.githubusercontent.com/1429994/104457468-591d0a80-5567-11eb-9ecf-6a5175fc8d0b.png)

**Comment by johnb8** [comment]
Oh yeah I'm using `friendly-errors-webpack-plugin` with `quiet: true` in the `devServer` settings of webpack. It gives an app-config error when I open the project in my browser, kind of confusing to see different errors in the browser and the terminal though, but this might be more of a me problem. I do see the same as you when I run the example project with a bad config.

**Comment by joelgallant** [comment]
Let's keep this issue open - there's probably metadata we can attach to these errors so that that plugin shows them better.

**Comment by joelgallant** [comment]
@johnb8 is this still confusing, with our changes in 2.3? I think the errors should be nicer now

**Comment by johnb8** [comment]
Nope, seems to be fixed. Thanks!
