### ISSUE TITLE
Explore ergonomic access to `__dirname` in a parsing extension

### ISSUE THREAD

**Issue by gregnr** [launchcodedev/app-config#96]
## Problem
As more extensions are built, the ability to reference relative files is important:

_.app-config.yml_
```yaml
$exec: node ./my-script.js
```

The problem is if another config file wanted to extend the above config:

_./sub-project/.app-config.yml_
```yaml
$extends: ../.app-config.yml
```

`$extends` will bring in the `$exec` command as-is, and `my-script.js` will not run because it exists relative to the root config file, not the sub-project. 

## Proposal 
Some sort of app-config concept or directive that supports `__dirname`-like behaviour. It would likely need to work closely with `$extends`. 

Ideas:
- Include this in `$substitute` somehow. Possibly a special injected `$APP_CONFIG_DIRNAME` that resolves to the current config file's absolute path 
- A separate directive, like `$dirname` that does something similar. Would require some sort of templating 
- A value-parsed extension? Something like `$exec: node __dirname/my-script.js` that looks for `__dirname` and replaces with absolute path
- Anything else more ergonomic?

**Comment by joelgallant** [comment]
I think I understand the need here. `$extends` does the same thing.

```javascript
import { FileSource } from '@lcdev/app-config';

function myExtension(keyName, meta) {
  return (value, [_, key]) => {
    return async (parse, _, context) => {
      if (context instanceof FileSource) {
        const fileDirectory = dirname(context.filePath);

        // ...
      }
    }
  }
}
```

Note that there's also logic to check if the given filepath is absolute. Of course, a __dirname relative file is meaningless when reading from `APP_CONFIG`.

I wonder how this functionality could be exposed better? Or just documented better?

**Comment by joelgallant** [comment]
We could build `@app-config/extension-utils` that exports:

- Utility to get current contextual directory / filename
- Utility for options validation (runtypes, ajv, or io-ts maybe)

Maybe others in the future

**Comment by joelgallant** [comment]
See https://github.com/launchcodedev/app-config/commit/2483a9381d731e8f4f7722214db342bdb3eb2886
